# Karaoke Jukebox - Docker Image (multi-stage)
#
# Stage 1 (export): a throwaway uv builder that regenerates requirements.txt
# FROM the committed uv.lock - the single source of truth for dependencies.
# uv lives ONLY in this stage; it never enters the runtime image.
#
# Stage 2 (base): the pip-native runtime. It copies the generated
# requirements.txt from stage 1 and `pip install`s it. No uv at run time.
#
# Because requirements.txt is generated here at build time, it is NOT committed
# to git (it is .gitignored). This keeps uv.lock as the only dependency manifest
# in the repo, so Dependabot updates uv.lock directly instead of a generated
# projection. To bump deps: update uv.lock (uv sync / Dependabot), rebuild.

# ----------------------------------------------------------------------------
# Stage 1: export requirements.txt from uv.lock
# ----------------------------------------------------------------------------
FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS export

WORKDIR /app

# Only the dependency manifests are needed to export - keeps this layer cached
# unless pyproject.toml or uv.lock actually change.
COPY pyproject.toml uv.lock ./

# Runtime deps only (--no-dev), no hashes, and drop the project itself
# (--no-emit-project) so pip installs third-party packages, not karaoke-jukebox.
RUN uv export --frozen --no-dev --no-hashes --no-emit-project -o requirements.txt

# ----------------------------------------------------------------------------
# Stage 2: pip-native runtime image
# ----------------------------------------------------------------------------
FROM python:3.13-slim AS base

# Set Python environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Required runtime environment variables (pass via -e or docker-compose):
# - ADMIN_PASSWORD: Admin user password (required)
# - YOUTUBE_API_KEY: YouTube Data API v3 key (required)
# - SECRET_KEY: Session signing key - generate with: python -c "import secrets; print(secrets.token_hex(32))"
# - SERVER_HOST: Docker host IP address (REQUIRED for Chromecast, e.g., 192.168.1.100)
# - SERVER_PORT: External port for Chromecast access (default: 5051)
# - DATA_DIR: Data directory path (default: /app/data)
# - LOG_LEVEL: Logging level (default: INFO)

# Install system dependencies
# - ffmpeg: Required for yt-dlp video downloads and processing
# - curl: Useful for health checks and the deno installer
# - unzip: required by the deno install script
# NOTE. Set DOCKER_BUILDKIT=1 for caching
RUN --mount=type=cache,target=/var/cache/apt,id=apt_cache \
    --mount=type=cache,target=/var/lib/apt,id=apt_lists \
    apt-get update && apt-get install -y --no-install-recommends \
    unzip ffmpeg curl

# install deno for yt-dlp (the EJS JS-challenge solver runs on deno at runtime)
ENV DENO_INSTALL="/usr/local"
ENV PATH="$DENO_INSTALL/bin:$PATH"
RUN curl -fsSL https://deno.land/install.sh | sh -s -- --yes

# Create app directory
WORKDIR /app

# Copy the requirements.txt generated by the export stage (for layer caching)
COPY --from=export /app/requirements.txt .

# Install Python dependencies
RUN pip install -r requirements.txt

# Self-healing yt-dlp layer:
# YouTube changes break yt-dlp periodically. Pull the latest yt-dlp on every
# image rebuild so a fresh build always ships a current downloader, even if
# uv.lock has drifted behind upstream.
RUN pip install --no-cache-dir -U "yt-dlp[default]"

# Copy application code
COPY app/ ./app/

# Create a non-root user and give it ownership of the data directory.
# gunicorn runs as this user (never root) for defense in depth.
RUN useradd --create-home --uid 10001 jukebox && \
    mkdir -p /app/data/videos && \
    chown -R jukebox:jukebox /app/data && \
    chmod -R 755 /app/data

# Expose port
EXPOSE 5051

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
    CMD curl -f http://localhost:5051/health || exit 1

# Drop privileges before running the server
USER jukebox

# Run with gunicorn using uvicorn workers
# - bind to 0.0.0.0:5051 to accept external connections
# - 1 worker (Chromecast playback state lives in-process; do not scale blindly)
# - uvicorn worker class for async support
# - timeout 120s for long-running operations (video downloads)
# - access log to stdout
CMD ["gunicorn", \
     "app.main:app", \
     "--bind", "0.0.0.0:5051", \
     "--workers", "1", \
     "--worker-class", "uvicorn.workers.UvicornWorker", \
     "--timeout", "120", \
     "--access-logfile", "-", \
     "--error-logfile", "-", \
     "--log-level", "info"]
